### ISSUE TITLE
question: webextension and webauthn

### ISSUE THREAD

**Issue by jschoch** [tanguilp/asteroid#7]
I'm wondering if you think asteroid would work for authenticating a browser extension with resident keys and what would be required to make it secure?

**Comment by tanguilp** [comment]
I'm not sure what you mean. What type of authentication would occur: user or device / client authentication? Which keys are resident: private or public keys? How are these keys deployed in the extension?

**Comment by jschoch** [comment]
sorry, the user would have a CTAP device with resident keys.  they would open the extension and then autenticate (or register without a username) via webauthn.

**Comment by tanguilp** [comment]
Well the browser extension would be the client in this case. When using FIDO2/WebAuthn you authenticate against a remote server, which will grant you an authentication token upon presentation of correct credentials.

This authentication can be a cookie, an ID Token, an OAuth2 token... If you want your extension to access an API, you could consider using OAuth2 tokens, issued after successful WebAuthn authentication. Does it make sense to you?

Also note that WebAuthn is necessarily web authentication, so you'll need to show the web authentication page at some point. You cannot do WebAuthn API-style.
